### ISSUE TITLE
Неправильная ссылка в Readme

### ISSUE THREAD

**Issue by dan-sazonov** [blackcatprog/VK-DCaP#1]
В ридми ссылка на vkhost указана как относительная, из-за чего сайт не открывается. 
Для решения проблемы ее можно заменить на абсолютную (`https://vkhost.github.io/`).

**Comment by eremeyko** [comment]
Ссылка всё равно некорректная. При переходе перекидывает сюда: [https://github.com/blackcatprog/VK-DCaP/blob/main/vkhost.github.io](url). Хотя по сути должно сюда: [https://vkhost.github.io/](url)

**Comment by dan-sazonov** [comment]
@eremeyko   Я предложил пр  #2, который решает эту проблему
